"""Adding cards

Revision ID: 0f7f7a38c035
Revises: 819bd843129e
Create Date: 2022-01-29 14:32:53.350195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7f7a38c035'
down_revision = '819bd843129e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cardtype', sa.String(length=30), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('PersonId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PersonId'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_card')
    # ### end Alembic commands ###
