"""Added Position

Revision ID: 1a38b97d69f4
Revises: f3e4184c636e
Create Date: 2022-01-25 13:37:26.902807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a38b97d69f4'
down_revision = 'f3e4184c636e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('position', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'position')
    # ### end Alembic commands ###
