"""Adding cards2

Revision ID: 816aefc36251
Revises: 0f7f7a38c035
Create Date: 2022-01-29 14:38:54.807541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816aefc36251'
down_revision = '0f7f7a38c035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_card', sa.Column('Datum', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_card', 'Datum')
    # ### end Alembic commands ###
